### PR TITLE
Add initial optimization formulation

### PR DESCRIPTION
**Pull request by gmantegna**
Add optimization module with OptimizedNetwork class, and associated tests. All tests are passing.

### CODE REVIEW

**Comment by manuel-k2** [comment]
Deployment still has to be fixed so don't bother about this failed check!

**Review by manuel-k2 — COMMENTED** [review]
Do you want to keep it in a notebook or do you plan on transferring it in a normal .py file?  Currently .ipynb files are listed in the .gitignore file but we could change that.

**Comment by gmantegna** [comment]
I’m going to be moving it to real python code, this is just experimentation

**Comment by jalalbutt** [comment]
Incorporated origin/main edits into optimization's __init__.py to resolve conflicts.

**Pull request merged**
